In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
import numpy as np
from sklearn.datasets import load_iris

In [16]:
iris = load_iris()

In [22]:

svc_score = cross_val_score(SVC(),iris.data,iris.target)
svc_score


array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [23]:
np.average(svc_score)

0.9666666666666666

In [18]:

l_score = cross_val_score(LogisticRegression(),iris.data,iris.target)
l_score

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [19]:

dt_score = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
dt_score

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [20]:

rf_score = cross_val_score(RandomForestClassifier(),iris.data,iris.target)
rf_score

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])